CREATE EXTERNAL TABLE u<X>.UK_weather (
  SITE_CODE                 STRING,
  SITE_NAME                 STRING,
  COUNTRY                   STRING,
  CONTINENT                 STRING,
  START_TIME                STRING,
  DAY                       STRING,
  DATE_MEASURE              STRING,
  TIME_STEP                 STRING,
  TIMESTAMP_MEASURE         STRING,
  WIND_DIRECTION            STRING,
  WIND_SPEED                BIGINT,
  SCREEN_TEMPERATURE        BIGINT,
  SIGNIFICANT_WEATHER       STRING,
  RELATIVE_HUMIDITY         BIGINT,
  VISIBILITY_RANGE          STRING,
  VISIBILITY_DESCRIPTION    STRING,
  WIND_GUST                 STRING,
  FEELS_LIKE_TEMPERATURE    BIGINT,
  UV_INDEX                  BIGINT,
  PRECIPITATION_PROBABILITY BIGINT
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\;'
LINES TERMINATED BY '\n' STORED AS TEXTFILE
LOCATION '/user/user<X>/UK_weather';
